# Generated by Django 5.2.15 on 2026-09-02 18:46
# Preserve the migration identity already applied by existing installations.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventree_quote_generator', '0002_quote_letterhead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quote',
            new_name='inventree_q_status_caae15_idx',
            old_name='inventree_q_status_1d39aa_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='inventree_q_custome_eec6d5_idx',
            old_name='inventree_q_custome_77443f_idx',
        ),
    ]
